name: Publish Python to PyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest

    # IMPORTANT: this permission is mandatory for trusted publishing
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: setuptools
      run: pip install -U setuptools pandas

    - name: Install pypa/build
      run: >-
        python -m pip install build --user

    # - name: ddddd
    #   run: python setup.py sdist

    - name: Build a binary wheel and a source tarball
      #run: python -m build --sdist --wheel --outdir dist/ .
      run: python -m build --wheel --outdir dist/ .


    - name: Publish distribution 📦 to PyPI
      #if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}



    # dddd
    # https://stackoverflow.com/questions/14547631/python-locale-error-unsupported-locale-setting
    - name: Locales
      run: >-
        sudo apt-get update && sudo apt-get install tzdata locales -y
        # sudo apt-get install language-pack-pt
        # sudo dpkg-reconfigure locales
