# dddd
site_name: Brazilian Holidays
docs_dir: .
site_dir: ../site

# NavBar
# Opcional
nav:
  - Home: index.md
  - Dois: pages/docs.md

# Theme
# Opcional
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - pymdownx.emoji # Suporte a emojis
  - pymdownx.tasklist # Suporte à tarefas
  - pymdownx.mark # Marcado
  - pymdownx.tilde  # Realçado
  - pymdownx.highlight  # Código
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Referências
# https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/mkdocs.yml