# https://blog.elmah.io/deploying-a-mkdocs-documentation-site-with-github-actions/

name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install mkdocs
      - run: mkdocs gh-deploy --force --clean --verbose
